/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#400040",
        "on-secondary-container": "#d9fffe",
        "error-dim": "#d73357",
        "secondary-fixed": "#00fbfb",
        "primary-dim": "#ed6ae9",
        "inverse-surface": "#fcf8f8",
        "on-secondary-fixed": "#004747",
        "error": "#ff6e84",
        "primary": "#ff7afb",
        "surface-bright": "#2c2c2c",
        "inverse-primary": "#a221a4",
        "secondary-container": "#006a6a",
        "on-secondary": "#005c5c",
        "primary-fixed": "#fc77f8",
        "surface-container-highest": "#262626",
        "tertiary-fixed": "#ff81f5",
        "on-primary-fixed": "#250026",
        "secondary-fixed-dim": "#00ecec",
        "error-container": "#a70138",
        "on-primary-container": "#440046",
        "surface-dim": "#0e0e0e",
        "primary-container": "#f06cec",
        "surface-container": "#1a1919",
        "outline": "#777575",
        "primary-fixed-dim": "#ed6ae9",
        "tertiary": "#ff51fa",
        "surface-container-lowest": "#000000",
        "on-surface-variant": "#adaaaa",
        "tertiary-dim": "#ff51fa",
        "surface-container-high": "#201f1f",
        "surface-container-low": "#131313",
        "surface-variant": "#262626",
        "on-surface": "#ffffff",
        "surface-tint": "#ff7afb",
        "tertiary-container": "#fe00fe",
        "on-tertiary-fixed": "#320032",
        "on-primary-fixed-variant": "#620065",
        "outline-variant": "#494847",
        "inverse-on-surface": "#565554",
        "on-tertiary-container": "#230023",
        "secondary": "#00fbfb",
        "on-secondary-fixed-variant": "#006666",
        "tertiary-fixed-dim": "#ff61f8",
        "on-background": "#ffffff",
        "on-error": "#490013",
        "on-error-container": "#ffb2b9",
        "secondary-dim": "#00ecec",
        "surface": "#0e0e0e",
        "background": "#0e0e0e",
        "on-tertiary-fixed-variant": "#6a006a",
        "on-primary": "#57005a",
        accent: '#06b6d4',
        dark: {
          100: '#1e1e2f',
          200: '#151522',
          300: '#0f0f1a',
          400: '#05050f',
        }
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "anime": ["Poppins", "sans-serif"],
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
      animation: {
        'glow': 'glow 2s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'float-slow': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-up': 'slideUp 0.8s ease-out forwards',
        'fade-in': 'fadeIn 1s ease-out forwards',
        'blob': 'blob 7s infinite',
        'shiny': 'shiny 2s infinite',
      },
      keyframes: {
        glow: {
          '0%, 100%': { textShadow: '0 0 5px #ff7afb, 0 0 10px #ff7afb' },
          '50%': { textShadow: '0 0 20px #ff7afb, 0 0 30px #00fbfb' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        shiny: {
          '0%': { transform: 'translateX(-100%) skewX(-15deg)' },
          '100%': { transform: 'translateX(200%) skewX(-15deg)' },
        }
      },
    },
  },
  plugins: [],
}